### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by HUIXIN-TW** [HUIXIN-TW/Portfolio#9]
Use GitHub Actions to automate the deployment process to GitHub Pages, ensuring that every time you push changes to your repository (or to specific branches), your site is automatically built and deployed. Here's a basic outline of how you can set up a GitHub Actions workflow for this purpose:

1. **Create a Workflow File:**
   - In your repository, create a new file in the `.github/workflows` directory. You can name it anything, for example, `deploy.yml`.

2. **Define the Workflow:**
   - In the `deploy.yml` file, define the workflow. Here's a basic example of what the content of the file might look like:

```yaml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the deployment from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: .  # The folder the action should deploy.
        # Add other necessary configurations like `token`, `repository-name` if needed.
```

In this workflow:

- It triggers on push to the specified branch (in this case, `main`).
- It uses the `actions/checkout@v2` action to checkout the code.
- It uses the `JamesIves/github-pages-deploy-action@4.1.4` to handle the deployment to GitHub Pages. This action takes care of building and deploying your site to the `gh-pages` branch (or any other branch you specify).

3. **Customize the Workflow:**
   - Modify the workflow to suit your needs. You might need to add build steps specific to your project (like installing dependencies, building your site, etc.).
   - Ensure the `folder` input in the `JamesIves/github-pages-deploy-action` step matches the directory where your built site files are located (it could be `build`, `dist`, or `.` if the built files are in the root).

4. **Commit and Push the Workflow File:**
   - Once you're done, commit the workflow file and push it to your repository.
   - GitHub Actions will automatically recognize the workflow file and start running the workflow whenever the specified trigger conditions are met.

With this setup, every time you push to the specified branch, GitHub Actions will run the workflow, build your site (if you have added build steps), and deploy the output to the specified deployment branch, automating your deployment process.
